require('onedark').setup({
  style = 'darker',
  highlights = {
    StartLogo1 = { fg = "#1C506B" },
    StartLogo2 = { fg = "#1D5D68" },
    StartLogo3 = { fg = "#1E6965" },
    StartLogo4 = { fg = "#1F7562" },
    StartLogo5 = { fg = "#21825F" },
    StartLogo6 = { fg = "#228E5C" },
    StartLogo7 = { fg = "#239B59" },
    StartLogo8 = { fg = "#24A755" },
    -----------------------------------------------------------
    NavicIconsFile = { bg = '$bg2', fg = '$blue' },
    NavicIconsModule = { bg = '$bg2', fg = '$blue' },
    NavicIconsNamespace = { bg = '$bg2', fg = '$blue' },
    NavicIconsPackage = { bg = '$bg2', fg = '$blue' },
    NavicIconsClass = { bg = '$bg2', fg = '$blue' },
    NavicIconsMethod = { bg = '$bg2', fg = '$blue' },
    NavicIconsProperty = { bg = '$bg2', fg = '$blue' },
    NavicIconsField = { bg = '$bg2', fg = '$blue' },
    NavicIconsConstructor = { bg = '$bg2', fg = '$blue' },
    NavicIconsEnum = { bg = '$bg2', fg = '$blue' },
    NavicIconsInterface = { bg = '$bg2', fg = '$blue' },
    NavicIconsFunction = { bg = '$bg2', fg = '$blue' },
    NavicIconsVariable = { bg = '$bg2', fg = '$blue' },
    NavicIconsConstant = { bg = '$bg2', fg = '$blue' },
    NavicIconsString = { bg = '$bg2', fg = '$blue' },
    NavicIconsNumber = { bg = '$bg2', fg = '$blue' },
    NavicIconsBoolean = { bg = '$bg2', fg = '$blue' },
    NavicIconsArray = { bg = '$bg2', fg = '$blue' },
    NavicIconsObject = { bg = '$bg2', fg = '$blue' },
    NavicIconsKey = { bg = '$bg2', fg = '$blue' },
    NavicIconsNull = { bg = '$bg2', fg = '$blue' },
    NavicIconsEnumMember = { bg = '$bg2', fg = '$blue' },
    NavicIconsStruct = { bg = '$bg2', fg = '$blue' },
    NavicIconsEvent = { bg = '$bg2', fg = '$blue' },
    NavicIconsOperator = { bg = '$bg2', fg = '$blue' },
    NavicIconsTypeParameter = { bg = '$bg2', fg = '$blue' },
    NavicText = { bg = '$bg2', fg = '$fg' },
    NavicSeparator = { bg = '$bg2', fg = '$red' },
  },
})

vim.cmd(':colorscheme onedark')
